# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionGrad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('alumnos', models.ManyToManyField(through='alumnos.AsignacionAlumno', to='alumnos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('materias', models.ManyToManyField(through='alumnos.AsignacionMat', to='alumnos.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='materias',
            field=models.ManyToManyField(through='alumnos.AsignacionGrad', to='alumnos.Materia'),
        ),
        migrations.AddField(
            model_name='asignacionmat',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Materia'),
        ),
        migrations.AddField(
            model_name='asignacionmat',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Profesor'),
        ),
        migrations.AddField(
            model_name='asignaciongrad',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Grado'),
        ),
        migrations.AddField(
            model_name='asignaciongrad',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Materia'),
        ),
        migrations.AddField(
            model_name='asignacionalumno',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Grado'),
        ),
    ]
